sug_award/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('vote.urls'))
]

vote/urls.py
from django.urls import path
from vote import views
from django.contrib.auth.views import logout_then_login

app_name = 'vote'


urlpatterns = [
    path('login', views.AuthLoginView.as_view(), name='login'),
    path('results/', views.result, name='result'),
    path('logout/',logout_then_login, name='logout'),
    path('index/', views.Index.as_view(), name='index'),
    path('', views.Index.as_view(), name='index')
]

vote/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    matric_number = models.CharField(max_length=20, unique=True)
    middle_name = models.CharField(max_length=30,null=True)


class Candidate(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    nick_name = models.CharField(max_length=20)

    def __str__(self):
        return '{} {} - ({})'.format(self.first_name,self.last_name,self.nick_name)

class VoteCategory(models.Model):
    name = models.CharField(max_length=225)
    candidates = models.ManyToManyField(Candidate)

    def __str__(self):
        return '<Category: {}>'.format(self.name)

    def is_eligible(self, user):
        return Vote.objects.filter(category=self, user=user).count() == 0
    
    @classmethod
    def eligible_category(cls, user):
        return VoteCategory.objects.exclude(vote__user=user)


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='voter')
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    category = models.ForeignKey(VoteCategory, on_delete=models.CASCADE)

    def __str__(self):
        return '{} - {}'.format(self.candidate.nick_name,self.category.name)

vote/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth import get_user_model
from vote.models import Vote, User


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}), label="Matric Number")
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text="One of your names"
    )
    
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password').lower()

        if username is not None and password:
            try:
                self.user_cache = User.objects.get(matric_number__iexact=username)
                if self.user_cache.first_name.lower() != password and self.user_cache.last_name.lower() != password and self.user_cache.middle_name.lower() != password :
                    raise self.get_invalid_login_error()
                else:
                    self.confirm_login_allowed(self.user_cache)
            except User.DoesNotExist:
                raise self.get_invalid_login_error()
        return self.cleaned_data


class VotingForm(forms.ModelForm):
    user = forms.CharField(required=False)
    class Meta:
        model = Vote
        fields = '__all__'
        widgets = {'category': forms.HiddenInput(), 'candidate': forms.RadioSelect()}

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request")
        super().__init__(*args, **kwargs)

    def clean_user(self):
        return self.request.user


class ImportExcelForm(forms.Form):
    file  = forms.FileField(label= "Choose excel to upload")    

vote/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.messages import success
from django.views.generic import FormView
from django.utils.decorators import method_decorator
from vote.forms import LoginForm, VotingForm
from vote.models import VoteCategory


@method_decorator(login_required, name='dispatch')
class Index(FormView):
    form_class = VotingForm
    template_name = 'index.html'
    success_url = reverse_lazy('vote:index')

    def get_context_data(self, **kwargs):
        """Insert the form into the context dict."""
        if 'categories' not in kwargs:
            kwargs['categories'] = VoteCategory.eligible_category(self.request.user)
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        vote = form.save()
        success(self.request, f'You have successfully voted for {vote.candidate} for {vote.category.name}')
        return super().form_valid(form)

    def get_form_kwargs(self):
        """Return the keyword arguments for instantiating the form."""
        kwargs = {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'request': self.request
        }

        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

class AuthLoginView(LoginView):
    authentication_form = LoginForm
    template_name = 'login.html'
    
    def get_success_url(self):
        return reverse('vote:index')


def result(request):
    if not request.user.is_staff or request.user.is_admin:
        return redirect('vote:index')
    return render('results.html')

def test_flowcell(request):
    c = RequestContext(request, {'other_context':'details here'})
    if request.method == 'POST': # If the form has been submitted...
        form = ImportExcelForm(request.POST,  request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            excel_parser= ExcelParser()
            success, log  = excel_parser.read_excel(request.FILES['file'] )
            if success:
                return redirect(reverse('admin:index') + "pages/flowcell_good/") ## redirects to aliquot page ordered by the most recent
            else:
                errors = '* Problem with flowcell * <br><br>log details below:<br>' + "<br>".join(log)
                c['errors'] = mark_safe(errors)
        else:
            c['errors'] = form.errors 
    else:
        form = ImportExcelForm() # An unbound form
    c['form'] = form
    return render_to_response('sequencing/file_upload.html')

vote/templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'css/layout.css'%}" />
    <link rel="shortcut icon" href="{% static 'img/SUG logo.jpg'%}" />
    <title>SUG AWARD</title>
  </head>
  <body>
    <nav
      class="navbar navbar-expand-md navbar-light bg-transparent sticky-top"
    >
      <div class="container">
        <div class="d-block">
          <a class="navbar-brand" href="{% url 'vote:index'%}">
            <img
              class="rounded p-0 "
              src="/static/img/suga awards logos.jpeg"
              width="100"
              height="50"
              alt="sug logo"
            />
          </a>
        </div>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navba"
          aria-controls="navigation-index"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon text-dark"></span>
        </button>
        <div class="collapse navbar-collapse  " id="navba">
          <ul class="navbar-nav ">
            <li class="nav-item active">
              <a class="nav-link" href="url 'vote:index'">Home </a>
            </li>

            {% if request.user.is_authenticated %}
            <div class="float-right">
              <li class="nav-item ">
                <a href="{% url 'vote:logout' %}" class=" nav-link">Logout</a>
              </li>
            </div>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <hr class="light" />
    {% include 'messages.html' %}

    <div class="container">
      <div class="row justify-content-center">
        {% block content %} 
        {% endblock content %}
      </div>
    </div>
    <footer class="fixed-bottom footer row justify-content-center align-items-center">
      <div class="copyright text-center">
        &copy;
        <script>
          document.write(new Date().getFullYear());
        </script>
        made with <i class="fas fa-heart"></i> by
        <a href="https://www.github.io/nuksi911/my_portfolio" target="_blank"
          >Nuru Design</a
        >
      </div>
      <div class="text-center">
        <a class="navbar-brand" href="{% url 'vote:index'%}">
          <img
            class="rounded-circle"
            src="/static/img/SUG logo.jpg"
            width="50"
            height="50"
            alt="sug logo"
          />
        </a>
        <a class="navbar-brand" href="{% url 'vote:index'%}">
          <img
            class="rounded-circle"
            src="/static/img/FUT logo.jpg"
            width="50"
            height="50"
            alt="sug logo"
          />
        </a>
      </div>
    </footer>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
      integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
      crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/35068a7079.js"></script>
  </body>
</html>

vote/templates/index.html
{% extends 'base.html' %} {% load form_manip %} {% block content %}
<div class=" container">
  <div class="col-sm-12 col-md-6 col-lg-12">
    <h1 class="text-white">Kindly Vote For Your Selected Candidate</h1>
    {% for error in form.errors %}
    <div class="alert alert-danger">{{ error }}</div>
    {% endfor %} {% for category in categories %}
    <button
      type="button"
      class="btn btn-primary d-block mx-auto p-auto mb-4"
      data-toggle="collapse"
      data-target="#{{ category.id }}"
    >
      {{ category.name }}
    </button>
    <div class="collapse" id="{{ category.id }}">
      <form method="POST">
        <div class="form-group">
          {% csrf_token %}
          <h5>{{ category.name }}</h5>
          {{ form.category | add_value: category.id }}

          <div class="form-group">
            <div id="id_candidate">
              {% for candidate in category.candidates.all %}
              <div class="form-check">
                <input
                  class="form-check-input"
                  type="radio"
                  name="candidate"
                  id="id_candidate_{{ category.id }}_{{ candidate.id }}"
                  value="{{ candidate.id }}"
                  checked
                />
                <label
                  class="form-check-label"
                  for="id_candidate_{{ category.id }}_{{ candidate.id }}"
                >
                  {{ candidate }}
                </label>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="form-group">
          <input type="submit" class="btn btn-primary" />
        </div>
      </form>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

vote/templates/login.html
{% extends 'base.html' %}
{% block content %}

    <div class="col-sm-12 col-md-6">
       <div class="card card-login">
        <h1 class="card-title text-center"> Login To Vote </h1>
        <form class="form-horizontal" action="/login" method='POST'>
          <div class="card-header card-header-primary text-center">
                 
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                {% endif %}
                {% for field in form %}
                    {% csrf_token %}
                    <div class="form-group col-lg-6">
                        {{ field.label_tag }}
                        {{ field }}
                        <div class="alert alert-light">{{ field.help_text }} </div>
                    </div>
                {% endfor %}
            <div class="form-group">
                <input type="submit" class="btn btn-outline-primary mx-auto">
            </div>
        </form>
    </div>
    </div>
    
{% endblock content %}

vote/templates/messages.html
{% if messages %}
<div class="messages">
    {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}